GET http://localhost:3000/


#### get todos
GET http://localhost:3000/api/todos

### create todos
POST http://localhost:3000/api/todos
Content-Type: application/json
Accept: application/json

{
    "title": "testTodo",
    "content": "testContent"
}

### get one
GET http://localhost:3000/api/todos/4

### update
PUT  http://localhost:3000/api/todos/1
Content-Type: application/json
Accept: application/json

{
    "isDone": true
}

### DELETE
DELETE http://localhost:3000/api/todos/5

### SIGNUP
POST http://localhost:3000/api/signup
Content-Type: application/json
Accept: application/json

{
    "name": "username1",
    "email": "email@testtesas.com",
    "password": "testpass"
}

### login
POST http://localhost:3000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "email@testtesas.com",
    "password": "testpass"
}