services:
  back:
    container_name: hono-todo
    build: 
      context: ./my-app/
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source : "./my-app"
        target: "/app"
    command: node /app/dist/src/index.js
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/mydb
    volumes:
      - db-data-volume:/var/lib/postgres/data
    ports:
      - 5432:5432
    
volumes:
  db-data-volume: